# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    identifier: "about"
    weight: 10

  - name: Registration
    identifier: "registration"
    url: "#registration"
    weight: 20

  - name: Submissions
    identifier: "submissions"
    weight: 30

  - name: Program
    identifier: "program"
    weight: 40

  - name: Venue
    identifier: "venue"
    weight: 50

  - name: Organization
    identifier: "organization"
    weight: 60

  - name: Contact
    identifier: "venue"
    weight: 70

  - name: Partners
    identifier: "partners"
    weight: 80

  - name: Summer School
    identifier: "summer_school"
    url: "#summer"
    weight: 90

  - name: Activities
    url: sessions
    identifier: "activities"
    weight: 100

  # under Activities:
  - name: By day
    parent: "activities"
    url: sessions-by-day
    weight: 10
  - name: By type
    parent: "activities"
    url: sessions-by-type
    weight: 20
  - name: Schedule
    url: schedule
    # identifier: schedule
    weight: 20
  - name: Participants
    url: participants
    weight: 30
  - name: Travel
    url: travel
    weight: 40
  # - name: Keynotes
  #   url: keynotes
  #   weight: 40
  # - name: Committee
  #   url: committee
  #   weight: 50
