# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: "home"
    url: "/"
    weight: 10

  - name: About
    identifier: "about"
    url: "#about"
    weight: 20

  - name: Calls
    identifier: "calls"
    weight: 30

  - name: Important Dates
    parent: "calls"
    url: "#calls"
    weight: 10

  - name: Call for Papers
    parent: "calls"
    url: "cfp/"
    weight: 20

  - name: Call for Sponsorships
    parent: "calls"
    url: "cfs/"
    weight: 30

  - name: Keynotes
    url: "keynotes/"
    weight: 40

  - name: Program
    identifier: "program"
    url: "program/"
    weight: 50

  #   - name: Keynotes
  #     parent: "program"
  #     url: "#keynotes"
  #     weight: 10

  - name: Schedule
    parent: "program"
    url: "schedule/"
    weight: 20

  - name: Summer School (external)
    parent: "program"
    url: "https://www.actorproject.org/timbre-and-orchestration-summer-school"
    weight: 30

  - name: Social Activities
    parent: "program"
    url: "social/"
    weight: 40

  - name: Attend
    identifier: "attend"
    url: "attend/"
    weight: 60

  - name: Registration
    parent: "attend"
    url: registration
    weight: 10

  - name: Accommodation
    parent: "attend"
    url: accommodation
    weight: 20

  - name: Location
    parent: "attend"
    url: "#host"
    weight: 30

  - name: Venue & Travel
    parent: "attend"
    url: venue
    weight: 40

  - name: Sponsors
    identifier: "sponsors"
    url: "#sponsors"
    weight: 70

  - name: Organizers
    identifier: "organizers"
    url: "organizers/"
    weight: 80
